stages:
    - test
    - build

.test:
    stage: test
    only:
        - main
        - feature
    image: python:3.9-slim-buster
    script:
        - pip install pylint
        # - pylint app.py
        - echo "Currently running print statement"

build:
    stage: build
    image: docker:24.0.5
    services:
        - docker:24.0.5-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
        IMAGE_NAME: harshadat/flask-rest-api
        IMAGE_TAG: python-app-3.0
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker run -d -p 5005:5000 $IMAGE_NAME:$IMAGE_TAG
        - sleep 10
        - apk update # Update the package index
        - apk add curl
        - curl http://localhost:5005/store

# run:
#     stage: run
#     script:
#         - docker run -d -p 5005:5000 $IMAGE_NAME:$IMAGE_TAG


